### ISSUE TITLE
Allow Blacklisting also

### ISSUE THREAD

**Issue by shahidmau** [tcdl/json-masker#13]
Is there any way to allow **blacklisting** instead of **whitelisting**, so we will mention the fields name to be masked and remaining fields will not be masked.

**Comment by sergiv83** [comment]
@shahidmau We thought about this feature and decided to not add it to the lib. It's potentially dangerous. In the case of typo or misconfiguration with the whitelisting approach, you'll have the field masked and will not see the original value. In contrast to that with the blacklisting approach, the value can appear unmasked. It can bring lots of problems. For example, we stored our logs to the 3-rd party service for aggregation and had to be sure that customer PI information will not appear unmasked in these logs for any case.
